apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guacamole

resources:
  - namespace.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - statefulset.yaml
