apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-initdb
  namespace: guacamole
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Mi
