---
apiVersion: v1
kind: Service
metadata:
  name: guacamole-postgresql
  namespace: guacamole
  labels:
    app: guacamole-postgresql
spec:
  selector:
    app: guacamole-postgresql
  ports:
    - port: 5432
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: guacamole
  labels:
    app: guacamole
spec:
  ports:
    - name: guacamole-app
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: guacamole
